/**
 * Copyright (c) 2025 Ray <roydoy7@gmail.com>
 *
 * CompactSummaryItem - Displays compact summary messages with collapsible content
 * These are generated by the /compact command to summarize previous conversation
 */

import { useState, memo } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import type { MessageListItem, MessageContent } from '../../../preload/preload-types';
import { useLanguage } from '../../i18n/LanguageContext';

interface CompactSummaryItemProps {
  item: MessageListItem;
}

export const CompactSummaryItem = memo(function CompactSummaryItem({ item }: CompactSummaryItemProps) {
  const { t } = useLanguage();
  const [isExpanded, setIsExpanded] = useState(false);

  // Extract text content from MessageContent
  const getTextContent = (content: MessageContent | undefined): string => {
    if (!content) return '';
    if (typeof content === 'string') return content;
    if (Array.isArray(content)) {
      return content
        .filter((block): block is { type: 'text'; text: string } => block.type === 'text')
        .map(block => block.text)
        .join('\n');
    }
    return '';
  };

  const textContent = getTextContent(item.content);

  // Truncate content for preview (first 200 chars)
  const previewContent = textContent.length > 200
    ? textContent.substring(0, 200) + '...'
    : textContent;

  return (
    <div
      className="compact-summary-item"
      style={{
        display: 'flex',
        flexDirection: 'column',
        maxWidth: 'var(--chat-item-max-width)',
        margin: '0.75rem 0',
        padding: '0.75rem 1rem',
        backgroundColor: 'var(--bg-tertiary)',
        borderRadius: '8px',
        border: '1px solid var(--border)',
        borderLeft: '3px solid var(--accent)',
      }}
    >
      {/* Header with icon and title */}
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          gap: '0.5rem',
          marginBottom: '0.5rem',
          cursor: 'pointer',
        }}
        onClick={() => setIsExpanded(!isExpanded)}
      >
        {/* Summary icon */}
        <svg
          width="16"
          height="16"
          viewBox="0 0 24 24"
          fill="none"
          stroke="var(--accent)"
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
        >
          <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
          <polyline points="14 2 14 8 20 8" />
          <line x1="16" y1="13" x2="8" y2="13" />
          <line x1="16" y1="17" x2="8" y2="17" />
          <line x1="10" y1="9" x2="8" y2="9" />
        </svg>

        <span style={{ fontWeight: 600, color: 'var(--text-primary)', fontSize: '0.875rem' }}>
          {t.compactSummary?.title || 'Conversation Summary'}
        </span>

        <span style={{ fontSize: '0.75rem', color: 'var(--text-tertiary)', marginLeft: 'auto' }}>
          {t.compactSummary?.continuedFrom || 'Continued from previous context'}
        </span>

        {/* Expand/collapse indicator */}
        <svg
          width="14"
          height="14"
          viewBox="0 0 24 24"
          fill="none"
          stroke="var(--text-secondary)"
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
          style={{
            transform: isExpanded ? 'rotate(180deg)' : 'rotate(0deg)',
            transition: 'transform 0.2s ease',
          }}
        >
          <polyline points="6 9 12 15 18 9" />
        </svg>
      </div>

      {/* Content - collapsed or expanded */}
      <div
        style={{
          fontSize: '0.8125rem',
          color: 'var(--text-secondary)',
          lineHeight: '1.5',
          overflow: 'hidden',
          maxHeight: isExpanded ? 'none' : '4.5em',
          transition: 'max-height 0.3s ease',
        }}
      >
        {isExpanded ? (
          <ReactMarkdown remarkPlugins={[remarkGfm]}>
            {textContent}
          </ReactMarkdown>
        ) : (
          <div style={{ whiteSpace: 'pre-wrap' }}>{previewContent}</div>
        )}
      </div>

      {/* Expand/collapse button */}
      {textContent.length > 200 && (
        <button
          onClick={() => setIsExpanded(!isExpanded)}
          style={{
            marginTop: '0.5rem',
            padding: '0.25rem 0.5rem',
            fontSize: '0.75rem',
            color: 'var(--accent)',
            backgroundColor: 'transparent',
            border: 'none',
            cursor: 'pointer',
            alignSelf: 'flex-start',
          }}
        >
          {isExpanded
            ? (t.compactSummary?.collapse || 'Show less')
            : (t.compactSummary?.expand || 'Show full summary')}
        </button>
      )}
    </div>
  );
});
